### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by mattwigway** [conveyal/mastarm#13]
When proxying a backend service that I'm debugging, I frequently get the following when I restart the backend service or set a breakpoint that causes requests to time out. I'd prefer if that one request failed but did not bring down mastarm. Also in development mode, timeouts should be very long (5-10 minutes) because I would like to set breakpoints and step through backend code without disrupting the frontend:
```
[0122] 3ms         271B GET    200 /bundle/d8934e776e6f4e9abd2463e2fda9509f (middleware)
/Users/matthewc/conveyal/scenario-editor/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketCloseListener (_http_client.js:282:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:492:12)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! scenario-editor@0.0.1 start: `mastarm serve lib/index.js --proxy http://localhost:7070/api`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scenario-editor@0.0.1 start script 'mastarm serve lib/index.js --proxy http://localhost:7070/api'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scenario-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mastarm serve lib/index.js --proxy http://localhost:7070/api
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scenario-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scenario-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matthewc/conveyal/scenario-editor/npm-debug.log
Matthews-MacBook-Pro:scenario-editor matthewc$```

**Comment by trevorgerhardt** [comment]
Looks like we need to handle error events on the http-proxy, that may be able to prevent the hang up

**Comment by trevorgerhardt** [comment]
Pushed a fix in https://github.com/conveyal/mastarm/commit/897ae3bdc6a378cde3321de62376710c0618795c

but there are a lot of recent changes that I haven't tested with scenario editor yet. Read the docs if you're having trouble!

**Comment by trevorgerhardt** [comment]
Haven't published a new release yet

**Comment by mattwigway** [comment]
OK nbd, I'll just wait for a release.
