### ISSUE TITLE
Mastarm build is failing in Windows 10 OS

### ISSUE THREAD

**Issue by Nazarah** [conveyal/mastarm#235]
Hi,

I am trying to make a build in mastarm  and it throws the follwoing error.
I am using windows 10 pro 64-bit OS.
I am getting the following error:

C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\lib\util.js:11
    throw new Error(
    ^

Error: No file(s) found! Did you spell the filename(s) correctly?
    at Object.exports.assertEntriesExist (C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\lib\util.js:11:11)
    at Object.<anonymous> (C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\bin\mastarm-build:34:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Can you please help me out here?
Thanks

**Comment by trevorgerhardt** [comment]
From what I know this library is only used within Conveyal for Conveyal projects. 

What project are you using it for? What command are you running exactly?

**Comment by Nazarah** [comment]
Hi.
I am trying to install [Conveyal Transit Data Tools](http://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment/) which requires Mastram.

What I tried to do in later steps is to go inside cloned github repository folder and tried to initiate a build with the command mastarm build: `C:\Users\Omistaja\Documents\GitHub\datatools-ui>mastarm build`

Aftterwards I got the following error:
`Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'babel-polyfill' from 'C:\Users\Omistaja\Documents\GitHub\datatools-ui\lib'
    at C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Omistaja\AppData\Roaming\npm\node_modules\mastarm\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

C:\Users\Omistaja\Documents\GitHub\datatools-ui>`

I have decided to like solve one error at a time to see where it leads to. 
But thought of seeking suggestions from you.
